name: built_value_bug_demo
description: A demo of a bug in built_value error reporting when SDK collections are used.

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  built_value: ^6.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.0.0
  built_value_generator: ^6.6.0